package hrapp

import (
	"context"
	"github.com/pkg/errors"
	"github.com/prometheus/client_golang/prometheus"
	"go.uber.org/zap"
	"google.golang.org/grpc"
)

var (
	grpcReqs *prometheus.CounterVec
)

type ServiceImpl struct {
	logger      *zap.Logger
	serviceDesc grpc.ServiceDesc
	dbClient    EmployeeDB
}

func NewServiceImpl(logger *zap.Logger) *ServiceImpl {
	return &ServiceImpl{logger, _Hrapp_serviceDesc, nil}
}

//ServiceDesc() returns the GRPC service description generated by the proto file
func (s *ServiceImpl) ServiceDesc() *grpc.ServiceDesc {
	return &s.serviceDesc
}

func (s *ServiceImpl) Init() error {
	s.logger.Info("Initializing service")
	dbClient, err := DBInit(s.logger)
	if err != nil {
		return errors.Wrap(err, "EmployeeDB initialization failed")
	}
	s.dbClient = dbClient
	grpcReqs = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "grpc_requests_total",
			Help: "How many gRPC requests processed, partitioned by status code and HTTP method.",
		},
		[]string{"code", "method"},
	)
	prometheus.MustRegister(grpcReqs)
	return nil
}

func (s *ServiceImpl) Run() {
	s.logger.Info("Running	 service")
}

// Function to implement Business API
func (s *ServiceImpl) GetEmployee(ctx context.Context, id *EmployeeId) (*Employee, error) {
	s.logger.Debug("gRPC: GetEmployee called", zap.Int64("empId", id.Id))
	grpcReqs.WithLabelValues("200", "getemployee").Inc()
	return s.dbClient.GetEmployee(id)

}
